local opt = vim.opt

opt.number = true
opt.relativenumber = true
opt.tabstop = 2
opt.expandtab = true
opt.shiftwidth = 2
opt.cursorline = true
opt.backup = false
opt.clipboard = "unnamedplus"
opt.cmdheight = 1
opt.completeopt = { "menuone", "noselect" }
opt.conceallevel = 0
opt.fileencoding = "utf-8"
opt.foldmethod = "manual"
opt.foldexpr = ""
opt.showmode = false
opt.signcolumn = "yes"
opt.numberwidth = 4
opt.scrolloff = 8
opt.sidescrolloff = 8
opt.wrap = false
opt.ruler = false
opt.laststatus = 3
opt.hidden = true
opt.pumheight = 10
opt.smartcase = true
opt.termguicolors = true
opt.swapfile = false
opt.splitbelow = true
opt.splitright = true
opt.timeoutlen = 1000
opt.title = true
opt.undofile = true
